# docker-Specify the compose version
version: "3"

services:
  app:
    # build: .
    image: pudding/docker-image-base:action-UT-Podcast-Docker-Image-20241219.165948
    tty: true
    # command: "yt-dlp --print upload_date https://www.youtube.com/watch?v=51042w5wZsM"
    volumes: 
      - ./output:/output/
      - ./cache:/cache/
      - ./config-list.js:/config-list.js
      - ./config-json.js:/config-json.js
